package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DetalleFacturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaAllPropertiesEquals(DetalleFactura expected, DetalleFactura actual) {
        assertDetalleFacturaAutoGeneratedPropertiesEquals(expected, actual);
        assertDetalleFacturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaAllUpdatablePropertiesEquals(DetalleFactura expected, DetalleFactura actual) {
        assertDetalleFacturaUpdatableFieldsEquals(expected, actual);
        assertDetalleFacturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaAutoGeneratedPropertiesEquals(DetalleFactura expected, DetalleFactura actual) {
        assertThat(actual)
            .as("Verify DetalleFactura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaUpdatableFieldsEquals(DetalleFactura expected, DetalleFactura actual) {
        assertThat(actual)
            .as("Verify DetalleFactura relevant properties")
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecioUnitario())
                    .as("check precioUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioUnitario())
            )
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaUpdatableRelationshipsEquals(DetalleFactura expected, DetalleFactura actual) {
        assertThat(actual)
            .as("Verify DetalleFactura relationships")
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()))
            .satisfies(a -> assertThat(a.getFactura()).as("check factura").isEqualTo(expected.getFactura()));
    }
}
